configserver: true
bus: true

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

spring:
  data:
    mongodb:
      uri: ${MONGODB_URL:mongodb://127.0.0.1:27017/stores}
  rabbitmq:
    addresses: ${RABBITMQ_URL:amqp://guest:guest@127.0.0.1:5672}
    virtual-host: /

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port:8080}}
  client:
    password: eureka
      client:
        serviceUrl:
          defaultZone: ${EUREKA_SERVER_URL:http://user:${eureka.password}@127.0.0.1:8761/eureka/}

logging:
  level:
    ROOT: INFO
  path: ./logs
  pattern:
    file: ${spring.application.name}.%d{yyyy-MM-dd}.log
