configserver: true
bus: true

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

spring:
  data:
    mongodb:
      uri: ${MONGODB_URL:mongodb://192.168.60.41:27017/stores}
  rabbitmq:
    host: rabbitmq
    addresses: ${RABBITMQ_URL:amqp://guest:guest@192.168.60.41:5672}
    virtual-host: /

eureka:
  password: eureka
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL_1:http://user:${eureka.password}@192.168.60.41:8761/eureka/},${EUREKA_SERVER_URL_2:http://user:${eureka.password}@192.168.60.43:8761/eureka/}
  instance:
    preferIpAddress: false
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${EUREKA_INSTANCE_ID:${spring.application.name}:${spring.application.instance_id:${server.port:8080}}}

logging:
  level:
    ROOT: INFO
  pattern:
    file: ${spring.application.name}.%d{yyyy-MM-dd}.log
